import type { AppLanguage } from '@/lib/language';

const copy = {
  sq: {
    panelTitle: 'Paneli',
    boostCoins: 'Boost coins',
    addListing: 'Shto njoftim',
    statistics: 'Statistikat',
    myListings: 'Njoftimet e mia',
    buyCredits: 'Bli coins',
    subscriptionPackage: 'Paketa e abonimit',
    quotasHint: (plan: string, category: string) => `${plan} · ${category}`,
    apartments: 'Apartamente',
    cars: 'Makina',
    jobs: 'Vende pune',
    products: 'Produkte',
    premium: 'Premium',
    okazion: 'OKAZION',
    unavailable: 'Jo e disponueshme',
    remaining: (n: number) => `${n} të mbetura`,
    convertTooltip: 'Konverto në Boost Coins',
    convertAria: (label: string) => `Konverto kuotën ${label}`,
    packagesTitle: 'Paketat për ju',
    packagesDescription: 'Planet e abonimit — FREE, STARTER, GROW dhe ELITE.',
    extraPackagesTitle: 'Paketat shtesë',
    extraPackagesDescription: 'OKAZION, auto-refresh, premium listing dhe konvertim me Boost Coins.',
    referralTitle: 'Referimi (-20% Lifetime)',
    referralDescription: 'Ftoni miqtë dhe fitoni kredite nga sistemi i referimit.',
    paymentsTitle: 'Pagesat e mia',
    paymentsDescription: 'Shikoni pagesat, abonimet dhe historikun e transakcioneve.',
    profileTitle: 'Profili im',
    profileDescription: 'Menaxhoni të dhënat e llogarisë dhe fjalëkalimin.',
    termsTitle: 'Kushtet e përdorimit',
    termsDescription: 'Rregullat e platformës.',
    privacyTitle: 'Politika e privatësisë',
    privacyDescription: 'Si trajtohen të dhënat tuaja.',
    signOut: 'Dil nga llogaria',
  },
  en: {
    panelTitle: 'Dashboard',
    boostCoins: 'Boost coins',
    addListing: 'Add listing',
    statistics: 'Statistics',
    myListings: 'My listings',
    buyCredits: 'Buy coins',
    subscriptionPackage: 'Subscription package',
    quotasHint: (plan: string, category: string) => `${plan} · ${category}`,
    apartments: 'Apartments',
    cars: 'Cars',
    jobs: 'Jobs',
    products: 'Products',
    premium: 'Premium',
    okazion: 'OKAZION',
    unavailable: 'Unavailable',
    remaining: (n: number) => `${n} left`,
    convertTooltip: 'Convert to Boost Coins',
    convertAria: (label: string) => `Convert ${label} quota`,
    packagesTitle: 'Packages for you',
    packagesDescription: 'Subscription plans — FREE, STARTER, GROW and ELITE.',
    extraPackagesTitle: 'Extra packages',
    extraPackagesDescription: 'OKAZION, auto-refresh, premium listing, and Boost Coins conversion.',
    referralTitle: 'Referral (-20% Lifetime)',
    referralDescription: 'Invite friends and earn credits from the referral program.',
    paymentsTitle: 'My payments',
    paymentsDescription: 'View payments, subscriptions, and transaction history.',
    profileTitle: 'My profile',
    profileDescription: 'Manage your account details and password.',
    termsTitle: 'Terms of use',
    termsDescription: 'Platform rules and conditions.',
    privacyTitle: 'Privacy policy',
    privacyDescription: 'How your data is handled.',
    signOut: 'Sign out',
  },
} as const;

export type UserDashboardCopy = (typeof copy)[AppLanguage];

export function getUserDashboardCopy(language: AppLanguage): UserDashboardCopy {
  return copy[language];
}
